---
version: 2
jobs:
  run-tests: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build plugin
          command: yarn prepack
      - run:
          name: Testing
          command: yarn test

# TODO Publish to NPM on push to master...

workflows:
  version: 2
  "sfdx-executor":
    jobs:
      - run-tests
